import ts from 'typescript'
import { CliFileWriter } from '../../cli/CliFileWriter.js'
import { IntrospectedColumn, IntrospectedTable } from '../../types/db.js'
import camelize from '../camelize.js'
import pascalize from '../pascalize.js'
import ASTConnectionBuilder, { DB_TYPES_RESERVED_NAMES } from './ASTConnectionBuilder.js'
import autogeneratedFileDisclaimer from './autoGeneratedFileDisclaimer.js'

/**
 * Writes a connection's types/db.ts (types/db.<connectionName>.ts for any
 * connection but default) from its introspection: the Kysely `DB`
 * interface, an interface for each table, each enum the tables use as a
 * union of its values with a `<Enum>Values` const of them, and the column
 * types those declare. Columns that the table's models ignore are left out,
 * so that code still referring to one fails to compile.
 */
export default class ASTDbTypesBuilder extends ASTConnectionBuilder {
  public async build() {
    const database = await this.introspectedDatabase()
    const enumTypeNames = await this.enumTypeNames(DB_TYPES_RESERVED_NAMES)
    const takenNames = new Set([...DB_TYPES_RESERVED_NAMES, ...enumTypeNames.values()])
    const usedTypes = new Set<string>()

    const tables = database.tables.map(table => ({
      key: this.tableKey(table),
      interfaceName: uniqueName(pascalize(this.tableKey(table).replace('.', '_')), takenNames),
      columns: this.columns(table, enumTypeNames, usedTypes),
    }))

    const typeStatements: { name: string; text: string }[] = HELPER_TYPE_NAMES.filter(name =>
      usedTypes.has(HELPER_TYPE_GROUPS[name] ?? name)
    ).map(name => ({ name, text: HELPER_TYPE_DECLARATIONS[name]! }))

    for (const databaseEnum of database.enums) {
      const typeName = enumTypeNames.get(databaseEnum.name)
      if (!typeName) continue

      const values = [...databaseEnum.values].sort((a, b) => a.localeCompare(b)).map(quote)
      typeStatements.push({
        name: typeName,
        text: `export type ${typeName} = ${values.join(' | ')}\n\nexport const ${typeName}Values = [${values.join(', ')}] as const`,
      })
    }

    const tableStatements = [...tables]
      .sort((a, b) => a.interfaceName.localeCompare(b.interfaceName))
      .map(
        table =>
          `export interface ${table.interfaceName} {\n${table.columns
            .map(column => `  ${propertyKey(column.key)}: ${column.type}`)
            .join('\n')}\n}`
      )

    const dbMembers = tables.map(table => `  ${propertyKey(table.key)}: ${table.interfaceName}`).join('\n')

    const output = await this.prettier(`\
${autogeneratedFileDisclaimer()}
${this.imports(usedTypes)}

${[
  ...typeStatements.sort((a, b) => a.name.localeCompare(b.name)).map(statement => statement.text),
  ...tableStatements,
  `export interface DB {\n${dbMembers}\n}`,
  `export class DBClass {\n${dbMembers}\n}`,
].join('\n\n')}
`)

    await CliFileWriter.write(this.dbPath(), output)
  }

  /**
   * @internal
   *
   * the table's columns, minus those its models ignore, sorted by name, each
   * with its key (the camelized column name) and its type. Records in
   * usedTypes each declared type a column uses.
   */
  private columns(table: IntrospectedTable, enumTypeNames: Map<string, string>, usedTypes: Set<string>) {
    const ignoredColumns = this.ignoredColumnsForTable(this.tableKey(table))

    return [...table.columns]
      .sort((a, b) => a.name.localeCompare(b.name))
      .map(column => ({ key: camelize(column.name), type: columnType(column, enumTypeNames, usedTypes) }))
      .filter(column => !ignoredColumns.has(column.key))
  }

  /**
   * @internal
   *
   * the file's imports: Dream's date and time classes, Kysely's ColumnType,
   * and postgres-interval's type when a column is an interval
   */
  private imports(usedTypes: Set<string>) {
    const sourceFile = ts.createSourceFile('', '', ts.ScriptTarget.Latest, false, ts.ScriptKind.TS)
    const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed })

    return [
      ...this.dateAndDateTimeImports().map(node =>
        printer.printNode(ts.EmitHint.Unspecified, node, sourceFile)
      ),
      `import type { ColumnType } from 'kysely'`,
      ...(usedTypes.has('Interval') ? [`import type { IPostgresInterval } from 'postgres-interval'`] : []),
    ].join('\n')
  }
}

/**
 * The column's type in its table's interface: its value type (an array of
 * them for an array column), `| null` when it allows null, all wrapped in
 * `Generated<>` when an insert may leave it out.
 */
function columnType(column: IntrospectedColumn, enumTypeNames: Map<string, string>, usedTypes: Set<string>) {
  const valueType = column.valueType === 'enum' ? enumTypeNames.get(column.enumName!)! : column.valueType
  usedTypes.add(column.valueType)

  let type = valueType
  if (column.isArray) {
    if (PLAIN_ARRAY_VALUE_TYPES.includes(column.valueType)) {
      type = `${valueType}[]`
    } else {
      type = `ArrayType<${valueType}>`
      usedTypes.add('ArrayType')
    }
  }

  if (column.allowNull) type = `${type} | null`

  if (column.hasDefault) {
    type = `Generated<${type}>`
    usedTypes.add('Generated')
  }

  return type
}

/**
 * The value types an array column lists in a plain array. Any other is
 * listed through `ArrayType`, which turns a `ColumnType` (such as `Int8`)
 * into a `ColumnType` of arrays.
 */
const PLAIN_ARRAY_VALUE_TYPES: string[] = ['string', 'number', 'boolean', 'ClockTime', 'ClockTimeTz']

const HELPER_TYPE_DECLARATIONS: Record<string, string> = {
  ArrayType: 'export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[] ? U[] : ArrayTypeImpl<T>',
  ArrayTypeImpl:
    'export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S[], I[], U[]> : T[]',
  Circle: 'export type Circle = { x: number; y: number; radius: number }',
  Generated:
    'export type Generated<T> = T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>',
  Int8: 'export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>',
  Interval:
    'export type Interval = ColumnType<IPostgresInterval, IPostgresInterval | number | string, IPostgresInterval | number | string>',
  Json: 'export type Json = JsonValue',
  JsonArray: 'export type JsonArray = JsonValue[]',
  JsonObject: 'export type JsonObject = {\n  [x: string]: JsonValue | undefined\n}',
  JsonPrimitive: 'export type JsonPrimitive = boolean | number | string | null',
  JsonValue: 'export type JsonValue = JsonArray | JsonObject | JsonPrimitive',
  Numeric: 'export type Numeric = ColumnType<string, number | string, number | string>',
  Point: 'export type Point = { x: number; y: number }',
  Timestamp: 'export type Timestamp = ColumnType<DateTime | CalendarDate>',
}

const HELPER_TYPE_NAMES = Object.keys(HELPER_TYPE_DECLARATIONS)

/**
 * The helper types declared whenever another is used, keyed by the helper
 * and naming the one whose use brings it in.
 */
const HELPER_TYPE_GROUPS: Record<string, string> = {
  ArrayTypeImpl: 'ArrayType',
  JsonArray: 'Json',
  JsonObject: 'Json',
  JsonPrimitive: 'Json',
  JsonValue: 'Json',
}

function uniqueName(baseName: string, takenNames: Set<string>) {
  let name = baseName
  for (let suffix = 2; takenNames.has(name); suffix++) name = `${baseName}${suffix}`
  takenNames.add(name)
  return name
}

function propertyKey(key: string) {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? key : quote(key)
}

function quote(value: string) {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n').replace(/\r/g, '\\r')}'`
}
