import ts from 'typescript'
import { CliFileWriter } from '../../cli/CliFileWriter.js'
import { IntrospectedColumn, IntrospectedTable } from '../../types/db.js'
import camelize from '../camelize.js'
import ASTConnectionBuilder from './ASTConnectionBuilder.js'
import autogeneratedFileDisclaimer from './autoGeneratedFileDisclaimer.js'
import {
  dbTypesHelperNames,
  dbTypesName,
  dbTypesReservedNames,
  HELPER_TYPE_DECLARATIONS,
  PLAIN_ARRAY_VALUE_TYPES,
} from './dbTypesNaming.js'

/**
 * Writes a connection's types/db.ts (types/db.<connectionName>.ts for any
 * connection but default) from its introspection: the Kysely `DB`
 * interface, an interface for each table, each enum the tables use as a
 * union of its values with a `<Enum>Values` const of them, and the column
 * types those declare. Columns that the table's models ignore are left out,
 * so that code still referring to one fails to compile.
 */
export default class ASTDbTypesBuilder extends ASTConnectionBuilder {
  public async build() {
    const database = await this.introspectedDatabase()
    const enumTypeNames = await this.enumTypeNames()
    const helperNames = dbTypesHelperNames(database.tables)
    const takenNames = new Set([...dbTypesReservedNames(database.tables), ...enumTypeNames.values()])

    const tables = database.tables.map(table => ({
      key: this.tableKey(table),
      interfaceName: dbTypesName(this.tableKey(table), takenNames),
      columns: this.columns(table, enumTypeNames),
    }))

    const enumValues = new Map(database.enums.map(databaseEnum => [databaseEnum.name, databaseEnum.values]))
    const typeStatements = [
      ...helperNames.map(name => ({ name, text: HELPER_TYPE_DECLARATIONS[name]! })),
      ...[...enumTypeNames].map(([enumName, typeName]) => {
        const values = [...(enumValues.get(enumName) ?? [])].sort((a, b) => a.localeCompare(b)).map(quote)
        return {
          name: typeName,
          text: `export type ${typeName} = ${values.join(' | ') || 'never'}\n\nexport const ${typeName}Values = [${values.join(', ')}] as const`,
        }
      }),
    ]

    const tableStatements = [...tables]
      .sort((a, b) => a.interfaceName.localeCompare(b.interfaceName))
      .map(
        table =>
          `export interface ${table.interfaceName} {\n${table.columns
            .map(column => `  ${propertyKey(column.key)}: ${column.type}`)
            .join('\n')}\n}`
      )

    const dbMembers = tables.map(table => `  ${propertyKey(table.key)}: ${table.interfaceName}`).join('\n')

    const output = await this.prettier(`\
${autogeneratedFileDisclaimer()}
${this.imports(helperNames)}

${[
  ...typeStatements.sort((a, b) => a.name.localeCompare(b.name)).map(statement => statement.text),
  ...tableStatements,
  `export interface DB {\n${dbMembers}\n}`,
  `export class DBClass {\n${dbMembers}\n}`,
].join('\n\n')}
`)

    await CliFileWriter.write(this.dbPath(), output)
  }

  /**
   * @internal
   *
   * the table's columns, minus those its models ignore, sorted by name, each
   * with its key (the camelized column name) and its type
   */
  private columns(table: IntrospectedTable, enumTypeNames: Map<string, string>) {
    const ignoredColumns = this.ignoredColumnsForTable(this.tableKey(table))

    return [...table.columns]
      .sort((a, b) => a.name.localeCompare(b.name))
      .map(column => ({ key: camelize(column.name), type: columnType(column, enumTypeNames) }))
      .filter(column => !ignoredColumns.has(column.key))
  }

  /**
   * @internal
   *
   * the file's imports: Dream's date and time classes, Kysely's ColumnType,
   * and postgres-interval's type when a column is an interval
   */
  private imports(helperNames: string[]) {
    const sourceFile = ts.createSourceFile('', '', ts.ScriptTarget.Latest, false, ts.ScriptKind.TS)
    const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed })

    return [
      ...this.dateAndDateTimeImports().map(node =>
        printer.printNode(ts.EmitHint.Unspecified, node, sourceFile)
      ),
      `import type { ColumnType } from 'kysely'`,
      ...(helperNames.includes('Interval')
        ? [`import type { IPostgresInterval } from 'postgres-interval'`]
        : []),
    ].join('\n')
  }
}

/**
 * The column's type in its table's interface: its value type (an array of
 * them for an array column), `| null` when it allows null, all wrapped in
 * `Generated<>` when an insert may leave it out.
 */
function columnType(column: IntrospectedColumn, enumTypeNames: Map<string, string>) {
  const valueType = column.valueType === 'enum' ? enumTypeNames.get(column.enumName!)! : column.valueType

  let type = valueType
  if (column.isArray) {
    type = PLAIN_ARRAY_VALUE_TYPES.includes(column.valueType) ? `${valueType}[]` : `ArrayType<${valueType}>`
  }
  if (column.allowNull) type = `${type} | null`
  if (column.hasDefault) type = `Generated<${type}>`

  return type
}

function propertyKey(key: string) {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? key : quote(key)
}

function quote(value: string) {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n').replace(/\r/g, '\\r')}'`
}
