import ts from 'typescript'
import { CliFileWriter } from '../../cli/CliFileWriter.js'
import ASTBuilder from './ASTBuilder.js'
import autogeneratedFileDisclaimer from './autoGeneratedFileDisclaimer.js'

const f = ts.factory

/**
 * Responsible for building dream globals, which can be found at
 * types/dream.globals.ts.
 *
 * This class leverages internal AST building mechanisms built into
 * typescript to manually build up object literals and interfaces
 * for our app to consume.
 */
export default class ASTGlobalSchemaBuilder extends ASTBuilder {
  public async build() {
    // build a new, blank source file to populate with our output
    const sourceFile = ts.createSourceFile('', '', ts.ScriptTarget.Latest, false, ts.ScriptKind.TS)

    const output = await this.prettier(this.printStatements([this.buildGlobalTypeConfigConst()], sourceFile))

    await CliFileWriter.write(this.globalSchemaPath(), output)
  }

  /**
   * @internal
   *
   * builds up the `export const globalTypeConfig = ...` statement within the dream.globals.ts
   * file. It does this by leveraging low-level AST utils built into typescript
   * to manually build up an object literal, cast it as a const, and write it to
   * an exported variable.
   */
  private buildGlobalTypeConfigConst() {
    const globalTypeConfigObjectLiteral = f.createObjectLiteralExpression(
      [
        f.createPropertyAssignment(
          f.createIdentifier('serializers'),
          f.createArrayLiteralExpression(this.globalSerializerNames().map(key => f.createStringLiteral(key)))
        ),
      ],
      true // multiline
    )

    // add "as const" to the end of the schema object we
    // have built before returning it
    const constAssertion = f.createAsExpression(
      globalTypeConfigObjectLiteral,
      f.createKeywordTypeNode(ts.SyntaxKind.ConstKeyword as ts.KeywordTypeSyntaxKind)
    )

    const globalTypeConfigObjectLiteralConst = f.createVariableStatement(
      [f.createModifier(ts.SyntaxKind.ExportKeyword)],
      f.createVariableDeclarationList(
        [
          f.createVariableDeclaration(
            f.createIdentifier('globalTypeConfig'),
            undefined,
            undefined,
            constAssertion
          ),
        ],
        ts.NodeFlags.Const
      )
    )

    return globalTypeConfigObjectLiteralConst
  }

  /**
   * @internal
   *
   * writes the compiled statements to string.
   *
   */
  private printStatements(statements: ts.Node[], sourceFile: ts.SourceFile): string {
    const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed, omitTrailingSemicolon: true })
    const result = printer.printList(
      ts.ListFormat.SourceFileStatements,
      f.createNodeArray(statements),
      sourceFile
    )

    return `\
${autogeneratedFileDisclaimer()}
${result}`
  }
}
