import pluralize from 'pluralize-esm'
import serializerGlobalNameFromFullyQualifiedModelName from '../../serializer/helpers/serializerGlobalNameFromFullyQualifiedModelName.js'
import camelize from '../camelize.js'
import globalClassNameFromFullyQualifiedModelName from '../globalClassNameFromFullyQualifiedModelName.js'
import pascalize from '../pascalize.js'
import absoluteDreamPath from '../path/absoluteDreamPath.js'
import snakeify from '../snakeify.js'
import standardizeFullyQualifiedModelName from '../standardizeFullyQualifiedModelName.js'
import uniq from '../uniq.js'
import parseAttribute from './parseAttribute.js'
import validateStiChildColumns from './validateStiChildColumns.js'

interface GenerateDreamContentOptions {
  fullyQualifiedModelName: string
  columnsWithTypes: string[]
  fullyQualifiedParentName?: string | undefined
  connectionName?: string
  serializer: boolean
  includeAdminSerializers: boolean
  includeInternalSerializers?: boolean
  tableName?: string | undefined
  /** Model class name, computed once via modelClassNameFrom in the orchestrator. */
  modelClassName: string
  /**
   * When true, decorates the generated model with `@SoftDelete()` and adds a
   * `deletedAt` field to the model. Ignored for STI children (the `@SoftDelete()`
   * decorator is incompatible with STI children).
   */
  softDelete?: boolean
}

/**
 * Column names that are automatically emitted by the model generator (and
 * the migration generator). When the user passes any of these explicitly,
 * we filter them out of the attribute loop so the model class and migration
 * don't end up with duplicate declarations.
 */
const AUTO_GENERATED_TIMESTAMP_COLUMN_NAMES = ['created_at', 'updated_at', 'deleted_at'] as const

function columnName(columnWithType: string): string {
  return columnWithType.split(':')[0] ?? ''
}

export function hasExplicitColumn(columnsWithTypes: string[], name: string): boolean {
  return columnsWithTypes.some(col => columnName(col) === name)
}

export function filterAutoGeneratedTimestampColumns(columnsWithTypes: string[]): string[] {
  return columnsWithTypes.filter(
    col =>
      !AUTO_GENERATED_TIMESTAMP_COLUMN_NAMES.includes(
        columnName(col) as (typeof AUTO_GENERATED_TIMESTAMP_COLUMN_NAMES)[number]
      )
  )
}

export interface ModelConfig {
  fullyQualifiedModelName: string
  modelClassName: string
  parentModelClassName: string | undefined
  applicationModelName: string
  isSTI: boolean
  tableName: string
}

export interface ImportConfig {
  dreamTypeImports: string[]
  dreamImports: string[]
  modelImportStatements: string[]
}

export interface AttributeProcessingResult {
  content: string
  imports: string[]
}

export default function generateDreamContent(options: GenerateDreamContentOptions): string {
  const config = createModelConfig(options)
  if (config.isSTI) validateStiChildColumns(options.columnsWithTypes)

  // SoftDelete is incompatible with STI children, so it's only applied to
  // non-STI-child models.
  const includeSoftDelete = !config.isSTI && !!options.softDelete
  const hasExplicitDeletedAt = hasExplicitColumn(options.columnsWithTypes, 'deleted_at')
  // Filter out timestamp columns that we auto-generate from the attribute
  // processing loop so we don't double-generate them in the model class.
  // We only dedupe on non-STI models — STI children don't get auto timestamps.
  const columnsForAttributes = config.isSTI
    ? options.columnsWithTypes
    : filterAutoGeneratedTimestampColumns(options.columnsWithTypes)
  const attributesResult = processAttributes(columnsForAttributes, config.modelClassName)
  // Decorators is only referenced via `@deco.*` annotations on fields (e.g.,
  // BelongsTo, Encrypted). If the generated body emits none of those, the
  // import + declaration would trigger lint errors for unused identifiers,
  // so emit them commented out instead — keeps the boilerplate present for
  // the developer to uncomment when they add their first decorator.
  const decoratorsInUse = attributesResult.formattedDecorators.length > 0
  const baseImports = createImportConfig(config, options, {
    includeSoftDelete,
    includeDecorators: decoratorsInUse,
  })

  const allImports: ImportConfig = {
    ...baseImports,
    modelImportStatements: [...baseImports.modelImportStatements, ...attributesResult.imports],
  }

  const importSection = buildImportSection(allImports)
  const classDeclaration = buildClassDeclaration(config, { includeSoftDelete })
  const tableMethod = buildTableMethod(config)
  const serializersMethod = buildSerializersMethod(config, options)
  const fieldsSection = buildFieldsSection(config, attributesResult, {
    includeDeletedAt: includeSoftDelete || hasExplicitDeletedAt,
  })

  const decoBlock = decoratorsInUse
    ? `const deco = new Decorators<typeof ${config.modelClassName}>()

`
    : config.isSTI
      ? ''
      : `// Uncomment when adding decorators (@deco.BelongsTo, @deco.Validates, etc.):
// import { Decorators } from '@rvoh/dream'
// const deco = new Decorators<typeof ${config.modelClassName}>()

`

  return `${importSection}

${decoBlock}${classDeclaration}
${tableMethod}${serializersMethod}${fieldsSection}
}
`.replace(/^\s*$/gm, '')
}

export function createModelConfig(options: GenerateDreamContentOptions): ModelConfig {
  const fullyQualifiedModelName = standardizeFullyQualifiedModelName(options.fullyQualifiedModelName)
  const modelClassName = options.modelClassName
  const isSTI = !!options.fullyQualifiedParentName

  let parentModelClassName: string | undefined
  if (isSTI) {
    const standardizedParentName = standardizeFullyQualifiedModelName(options.fullyQualifiedParentName!)
    parentModelClassName = globalClassNameFromFullyQualifiedModelName(standardizedParentName)
  }

  const connectionName = options.connectionName || 'default'
  const applicationModelName =
    connectionName === 'default' ? 'ApplicationModel' : `${pascalize(connectionName)}ApplicationModel`

  const tableName = options.tableName || snakeify(pluralize(fullyQualifiedModelName.replace(/\//g, '_')))

  return {
    fullyQualifiedModelName,
    modelClassName,
    parentModelClassName,
    applicationModelName,
    isSTI,
    tableName,
  }
}

export function createImportConfig(
  config: ModelConfig,
  options: GenerateDreamContentOptions,
  { includeSoftDelete, includeDecorators = true }: { includeSoftDelete: boolean; includeDecorators?: boolean }
): ImportConfig {
  const dreamTypeImports: string[] = ['DreamColumn']
  const dreamImports: string[] = []
  if (includeDecorators) dreamImports.push('Decorators')

  if (options.serializer) {
    dreamTypeImports.push('DreamSerializers')
  }

  if (config.isSTI) {
    dreamImports.push('STI')
  }

  if (includeSoftDelete) {
    dreamImports.push('SoftDelete')
  }

  const baseModelName = config.isSTI ? options.fullyQualifiedParentName! : config.applicationModelName

  const modelImportStatements: string[] = [importStatementForModel(baseModelName)]

  return {
    dreamTypeImports,
    dreamImports,
    modelImportStatements,
  }
}

export function processAttributes(
  columnsWithTypes: string[],
  modelClassName: string
): AttributeProcessingResult & { formattedFields: string; formattedDecorators: string } {
  const attributeResults = columnsWithTypes.map(attribute => processAttribute(attribute, modelClassName))

  const allImports = attributeResults.flatMap(result => result.imports)

  const attributeStatements = attributeResults.map(result => result.content)

  const formattedFields = attributeStatements
    .filter(attr => !/^\n@/.test(attr))
    .map(s => s.split('\n').join('\n  '))
    .join('')

  const formattedDecorators = attributeStatements
    .filter(attr => /^\n@/.test(attr))
    .map(s => s.split('\n').join('\n  '))
    .join('\n  ')
    .replace(/\n {2}$/, '')

  return {
    content: '', // Not used in this context
    imports: allImports,
    formattedFields,
    formattedDecorators,
  }
}

export function processAttribute(attribute: string, modelClassName: string): AttributeProcessingResult {
  const [rawName, rawType] = attribute.split(':')

  if (rawName === undefined) return { content: '', imports: [] }
  if (!rawType) {
    throw new Error(`must pass a column type for ${rawName} (i.e. ${rawName}:string)`)
  }

  const parsed = parseAttribute(attribute)
  // Malformed-but-parseable shapes (e.g., `Model@:belongs_to` with an empty
  // alias) yield no content rather than throwing — the call site has already
  // validated the basic name/type segments above.
  if (!parsed) return { content: '', imports: [] }

  switch (parsed.normalizedAttributeType) {
    case 'belongsto':
      return createBelongsToAttribute(parsed.rawAttributeName, modelClassName, {
        aliasName: parsed.aliasName,
        isOptional: parsed.isOptional,
      })
    case 'hasone':
    case 'hasmany':
      return { content: '', imports: [] }
    case 'encrypted':
      return createEncryptedAttribute(parsed.rawAttributeName, attribute, modelClassName)
    default:
      return createRegularAttribute(parsed.rawAttributeName, attribute, modelClassName)
  }
}

export function createBelongsToAttribute(
  fullyQualifiedModelInput: string,
  modelClassName: string,
  {
    aliasName,
    isOptional = false,
  }: {
    aliasName?: string | undefined
    isOptional?: boolean
  } = {}
): AttributeProcessingResult {
  const fullyQualifiedAssociatedModelName = standardizeFullyQualifiedModelName(fullyQualifiedModelInput)
  const associationModelName = globalClassNameFromFullyQualifiedModelName(fullyQualifiedAssociatedModelName)
  const associationImportStatement = importStatementForModel(fullyQualifiedAssociatedModelName)

  const associationName = aliasName
    ? camelize(aliasName)
    : camelize(fullyQualifiedAssociatedModelName.split('/').pop()!)
  const associationForeignKey = `${associationName}Id`

  const content = `
@deco.BelongsTo('${fullyQualifiedAssociatedModelName}', { on: '${associationForeignKey}'${isOptional ? ', optional: true' : ''} })
public ${associationName}: ${associationModelName}${isOptional ? ' | null' : ''}
public ${associationForeignKey}: DreamColumn<${modelClassName}, '${associationName}Id'>
`

  return {
    content,
    imports: [associationImportStatement],
  }
}

export function createEncryptedAttribute(
  attributeName: string,
  attribute: string,
  modelClassName: string
): AttributeProcessingResult {
  const encryptedColumnName = camelize(`encrypted_${attributeName}`)
  const content = `
@deco.Encrypted()
public ${camelize(attributeName)}: DreamColumn<${modelClassName}, '${encryptedColumnName}'>`

  return {
    content,
    imports: [],
  }
}

export function createRegularAttribute(
  attributeName: string,
  attribute: string,
  modelClassName: string
): AttributeProcessingResult {
  const content = `
public ${camelize(attributeName)}: ${getAttributeType(attribute, modelClassName)}`

  return {
    content,
    imports: [],
  }
}

function buildImportSection(imports: ImportConfig): string {
  const dreamImportLine = imports.dreamImports.length
    ? `import { ${uniq(imports.dreamImports).join(', ')} } from '@rvoh/dream'\n`
    : ''

  const typeImportLine = `import { ${uniq(imports.dreamTypeImports).join(', ')} } from '@rvoh/dream/types'`
  const modelImports = uniq(imports.modelImportStatements).join('')

  return `${dreamImportLine}${typeImportLine}${modelImports}`
}

function buildClassDeclaration(
  config: ModelConfig,
  { includeSoftDelete }: { includeSoftDelete: boolean }
): string {
  const stiDecorator = config.isSTI ? `@STI(${config.parentModelClassName})\n` : ''
  const softDeleteDecorator = includeSoftDelete ? '@SoftDelete()\n' : ''
  const extendsClause = config.isSTI ? config.parentModelClassName : config.applicationModelName

  return `${stiDecorator}${softDeleteDecorator}export default class ${config.modelClassName} extends ${extendsClause} {`
}

function buildTableMethod(config: ModelConfig): string {
  if (config.isSTI) return ''

  return `  public override get table() {
    return '${config.tableName}' as const
  }

`
}

function buildSerializersMethod(config: ModelConfig, options: GenerateDreamContentOptions): string {
  if (!options.serializer) return ''

  const overrideKeyword = config.isSTI ? 'override ' : ''
  const defaultSerializer = serializerGlobalNameFromFullyQualifiedModelName(config.fullyQualifiedModelName)
  const summarySerializer = serializerGlobalNameFromFullyQualifiedModelName(
    config.fullyQualifiedModelName,
    'summary'
  )

  let adminSerializers = ''
  if (options.includeAdminSerializers) {
    const adminSerializer = defaultSerializer.replace(/Serializer$/, 'AdminSerializer')
    const adminSummarySerializer = summarySerializer.replace(/SummarySerializer$/, 'AdminSummarySerializer')
    adminSerializers = `
      admin: '${adminSerializer}',
      adminSummary: '${adminSummarySerializer}',`
  }

  let internalSerializers = ''
  if (options.includeInternalSerializers) {
    const internalSerializer = defaultSerializer.replace(/Serializer$/, 'InternalSerializer')
    const internalSummarySerializer = summarySerializer.replace(
      /SummarySerializer$/,
      'InternalSummarySerializer'
    )
    internalSerializers = `
      internal: '${internalSerializer}',
      internalSummary: '${internalSummarySerializer}',`
  }

  return `  public ${overrideKeyword}get serializers(): DreamSerializers<${config.modelClassName}> {
    return {
      default: '${defaultSerializer}',
      summary: '${summarySerializer}',${adminSerializers}${internalSerializers}
    }
  }

`
}

function buildFieldsSection(
  config: ModelConfig,
  attributes: { formattedFields: string; formattedDecorators: string },
  { includeDeletedAt }: { includeDeletedAt: boolean }
): string {
  if (config.isSTI) {
    return `${attributes.formattedFields}${attributes.formattedDecorators}`
  }

  const idField = `  public id: DreamColumn<${config.modelClassName}, 'id'>`
  const deletedAtLine = includeDeletedAt
    ? `\n  public deletedAt: DreamColumn<${config.modelClassName}, 'deletedAt'>`
    : ''
  let timestamps = `
  public createdAt: DreamColumn<${config.modelClassName}, 'createdAt'>
  public updatedAt: DreamColumn<${config.modelClassName}, 'updatedAt'>${deletedAtLine}
`

  if (!attributes.formattedDecorators.length) {
    timestamps = timestamps.replace(/\n$/, '')
  }

  return `${idField}${attributes.formattedFields}${timestamps}${attributes.formattedDecorators}`
}

function getAttributeType(attribute: string, modelClassName: string): string {
  return `DreamColumn<${modelClassName}, '${camelize(attribute.split(':')[0])}'>`
}

function importStatementForModel(destinationModelName: string): string {
  return `\nimport ${globalClassNameFromFullyQualifiedModelName(destinationModelName)} from '${absoluteDreamPath('models', destinationModelName)}'`
}
