models_path: 'test-app/app/models'
serializers_path: 'test-app/app/serializers'
client_api_schema_path: 'test-app/client/schema.ts'
conf_path: 'test-app/app/conf'
db_path: 'test-app/db'
db_seed_path: 'test-app/db/seed.ts'
unit_spec_path: 'test-app/spec/unit'
dreamconf_path: 'test-app/conf/dreamconf.ts'
