models_path: 'src/test-app/app/models'
migrations_path: 'src/test-app/db/migrations'
schema_path: 'src/test-app/db/schema.ts'
dream_config_path: 'src/test-app/conf/dream.ts'
db_path: 'src/test-app/db/index.ts'
