models_path: 'test-app/app/models'
serializers_path: 'test-app/app/serializers'
migrations_path: 'test-app/db/migrations'
associations_path: 'test-app/db/associations.ts'
schema_path: 'test-app/db/schema.ts'
dream_config_path: 'test-app/conf/dream.ts'
unit_spec_path: 'test-app/spec/unit'
feature_spec_path: 'test-app/spec/features'
serializer_casing: 'camel'
