nodeLinker: node-modules


npmPublishRegistry: "https://registry.npmjs.org"
npmPublishAccess: public

yarnPath: .yarn/releases/yarn-4.4.1.cjs

npmScopes:
  rvoh:
    npmAlwaysAuth: true
    npmRegistryServer: "https://registry.npmjs.org"
