
/*

                                    ,▄█▄                 
    ]█▄▄                         ╓█████▌                 
    ▐██████▄                   ▄█████▓╣█                 
     ║████████▄,  ,  ,,▄,▄▄▄▓██████╬╬╣╣▌                 
      ╚███╣██████████▓▓▓▓██████████╩╠╬▓                  
       ╙█╬╬╬▓███████████████████████▒▓▌                  
        ╙▓█▓██████████████████████████                   
         ╚██████▀███████████╩█▓▌▐▓████▄                  
         '║█████`╣█Γ║████████▄▄φ▓█████▌                 
          ║█████████████████████▓█████▌                  
           █████████████▓▓████████████                   
           ║█████████████████████████                    
          ]█████████████████████████                     
         ,▓██████████████████████████                    
        ▓█████████████████████████████µ                  
       ▐███████████████████████████████▄▄                
       ║█████████████████████████████████╬╬╣▓            
   ,╔╦║███████████████████████████████████▓╬╬╣           
,≥≥⌠░░░╠▓████████████████████████████████████▓▓          
,;=-',▄█████████████████████████████████████████▓        
                                                         
                                                         
                                                         
  ██████╗ ███████╗██╗   ██╗ ██████╗██╗  ██╗██╗ ██████╗   
  ██╔══██╗██╔════╝╚██╗ ██╔╝██╔════╝██║  ██║██║██╔════╝   
  ██████╔╝███████╗ ╚████╔╝ ██║     ███████║██║██║        
  ██╔═══╝ ╚════██║  ╚██╔╝  ██║     ██╔══██║██║██║        
  ██║     ███████║   ██║   ╚██████╗██║  ██║██║╚██████╗   
  ╚═╝     ╚══════╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝ ╚═════╝   
                                                         
                                                         

This file was automatically generated by my cat, Aster.
He does not want you mucking about with his files,
and we are pretty lax on trimming his nails.

I mean, we have him pretty well fenced in but he is an
escape artist and he still manages to get fleas!

My point is, don't go mucking about with his files!

He actually has a hopefully well-tempered message for
us humans, he says:

"
  Dear pathetic humans,

  Here is a haiku to keep you in line

  don't dare go mucking
  with my files, I lyke them fine
  prettierignore
"

*/

import type CalendarDate from '../../src/helpers/CalendarDate.js'
import { type DateTime } from '../../src/helpers/DateTime.js'


export const schema = {
  alternate_db_connection_users: {
    serializerKeys: ['default', 'summary'],
    scopes: {
      default: [],
      named: [],
    },
    nonJsonColumnNames: ['createdAt', 'email', 'id', 'name', 'updatedAt'],
    columns: {
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      email: {
        coercedType: {} as string,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as string,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      name: {
        coercedType: {} as string,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: false,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      
    },
  },
} as const

export const dreamTypeConfig = {
  passthroughColumns: [],
  allDefaultScopeNames: [],
  globalNames: {
    models: {
      'AlternateDbConnectionUser': 'alternate_db_connection_users',
      'Balloon/Latex/Animal': 'beautiful_balloons',
      'Balloon/Latex': 'beautiful_balloons',
      'Balloon/Mylar': 'beautiful_balloons',
      'Balloon': 'beautiful_balloons',
      'BalloonLine': 'balloon_lines',
      'BalloonSpotter': 'balloon_spotters',
      'BalloonSpotterBalloon': 'balloon_spotter_balloons',
      'CircularReference/LocalizedText': 'circular_reference_localized_texts',
      'CircularReference/ModelA': 'circular_reference_model_as',
      'CircularReference/ModelB': 'circular_reference_model_bs',
      'CircularReferenceModel': 'circular_reference_models',
      'Collar': 'collars',
      'Composition': 'compositions',
      'CompositionAsset': 'composition_assets',
      'CompositionAssetAudit': 'composition_asset_audits',
      'EdgeCaseAttribute': 'edge_case_attributes',
      'ExtraRating/Base': 'extra_ratings',
      'ExtraRating/HeartRating': 'extra_ratings',
      'ExtraRating/StarRating': 'extra_ratings',
      'Graph/Edge': 'graph_edges',
      'Graph/EdgeNode': 'graph_edge_nodes',
      'Graph/Node': 'graph_nodes',
      'IncompatibleForeignKeyTypeExample': 'incompatible_foreign_key_type_examples',
      'InvalidAssociationSortableModel': 'invalid_association_sortable_models',
      'InvalidScopeSortableModel': 'invalid_scope_sortable_models',
      'LocalizedText': 'localized_texts',
      'ModelForOpenapiTypeSpec': 'model_for_openapi_type_specs',
      'ModelWithDateTimeConditionalHooks': 'model_with_date_time_conditional_hooks',
      'ModelWithParamSafeAndUnsafeColumns': 'model_with_param_safe_and_unsafe_columns',
      'ModelWithParamUnsafeColumns': 'model_with_param_unsafe_columns',
      'ModelWithSerialPrimaryKey': 'model_with_serial_primary_keys',
      'ModelWithoutCustomDeletedAt': 'model_without_custom_deleted_ats',
      'ModelWithoutDeletedAt': 'model_without_deleted_ats',
      'ModelWithoutUpdatedAt': 'model_without_updated_at',
      'NonNullRating': 'ratings',
      'Pet': 'pets',
      'PetUnderstudyJoinModel': 'pet_understudy_join_models',
      'Polymorphic/Chore': 'polymorphic_chores',
      'Polymorphic/ChoreCleaningSupply': 'polymorphic_chore_cleaning_supplies',
      'Polymorphic/ChoreImage': 'polymorphic_chore_images',
      'Polymorphic/CleaningSupply': 'polymorphic_cleaning_supplies',
      'Polymorphic/Image': 'polymorphic_images',
      'Polymorphic/LocalizedText': 'polymorphic_localized_texts',
      'Polymorphic/MetaUser': 'polymorphic_meta_users',
      'Polymorphic/Task': 'polymorphic_tasks',
      'Polymorphic/TaskableImage': 'polymorphic_taskable_images',
      'Polymorphic/User': 'polymorphic_users',
      'Polymorphic/UserMetaUser': 'polymorphic_user_meta_users',
      'Polymorphic/Workout': 'polymorphic_workouts',
      'Polymorphic/WorkoutImage': 'polymorphic_workout_images',
      'Polymorphic/WorkoutType': 'polymorphic_workout_types',
      'Post': 'posts',
      'PostComment': 'post_comments',
      'PostVisibility': 'post_visibilities',
      'Rating': 'ratings',
      'Sandbag': 'sandbags',
      'Shape/Cat': 'shapes',
      'Shape/Regular': 'shapes',
      'Shape': 'shapes',
      'Through/A': 'through_as',
      'Through/AToOtherModelJoinModel': 'through_a_to_other_model_join_models',
      'Through/B': 'through_bs',
      'Through/MyModel': 'through_my_models',
      'Through/OtherModel': 'through_other_models',
      'UnscopedSortableModel': 'unscoped_sortable_models',
      'User': 'users',
      'UserSettings': 'user_settings'
    },
    serializers: [
      'AlternateDbConnectionUserSerializer',
      'AlternateDbConnectionUserSummarySerializer',
      'BallonLineSummarySerializer',
      'Balloon/DelegatedAttributeSerializer',
      'Balloon/Latex/AnimalSerializer',
      'Balloon/LatexSerializer',
      'Balloon/MylarSerializer',
      'BalloonLineSerializer',
      'BalloonSerializer',
      'BalloonSpotterBalloonSerializer',
      'BalloonSpotterSerializer',
      'BalloonSummarySerializer',
      'CircularReference/ModelASerializer',
      'CircularReference/ModelASummarySerializer',
      'CircularReference/ModelBSerializer',
      'CircularReference/ModelBSummarySerializer',
      'CircularReferenceModelSerializer',
      'CircularReferenceModelSummarySerializer',
      'CollarDeepSerializer',
      'CollarSerializer',
      'CollarSummarySerializer',
      'CompositionAlternateSerializer',
      'CompositionSerializer',
      'EdgeCaseAttributeSerializer',
      'ExtraRating/BaseExtraRatingSerializer',
      'ExtraRating/HeartRatingSerializer',
      'ExtraRating/StarRatingSerializer',
      'Graph/EdgeNodeSerializer',
      'Graph/EdgeSerializer',
      'Graph/NodeSerializer',
      'LocalizedText/BaseSerializer',
      'PetDeepDelegatedAttributeSerializer',
      'PetDeepSerializer',
      'PetSerializer',
      'PetSummarySerializer',
      'PetUnderstudyJoinModelSerializer',
      'Polymorphic/ChoreSerializer',
      'Polymorphic/CleaningSupplySerializer',
      'Polymorphic/ExplicitTaskableSerializer',
      'Polymorphic/ImageSerializer',
      'Polymorphic/ImageSummarySerializer',
      'Polymorphic/TaskSerializer',
      'Polymorphic/TaskWithExplicitRendersOneSerializer',
      'Polymorphic/UserSerializer',
      'Polymorphic/WorkoutSerializer',
      'Polymorphic/WorkouttypeSerializer',
      'PostSerializer',
      'PostVisibilitySerializer',
      'RatingDeepSerializer',
      'RatingSerializer',
      'SandbagSerializer',
      'ShapeSerializer',
      'ShapeSummarySerializer',
      'UserDeepSerializer',
      'UserSerializer',
      'UserSummarySerializer',
      'view-model/PetSerializer',
      'view-model/PetSummarySerializer',
      'view-model/UserSerializer',
      'view-model/UserSummarySerializer'
    ],
  },
} as const
