export default class CannotPaginateWithLimit extends Error {
  public override get message() {
    return `\
Cannot call paginate on a query which has a limit applied.

Limit statements are automatically generated by the paginate method,
and adding custom limits interferes with paginate's ability to provide
a total count.

fix:
  remove the limit statement from your query
`
  }
}
