export default class CannotPaginateWithOffset extends Error {
  public override get message() {
    return `\
Cannot call paginate on a query which has an offset applied.

Offset statements are automatically generated by the paginate method,
and adding custom offsets interferes with paginate's ability to provide
a total count.

fix:
  remove the offset statement from your query
`
  }
}
