import ModelWithSerialPrimaryKey from '../../../test-app/app/models/ModelWithSerialPrimaryKey.js'
import User from '../../../test-app/app/models/User.js'

// These models exercise the `generated by default as identity` primary key
// columns emitted by `generateIdStr`:
//   - User has a `bigint` identity id
//   - ModelWithSerialPrimaryKey has an `integer` identity id
// In both cases the database fills the id when none is provided, and (because
// the columns are `BY DEFAULT`, not `ALWAYS`) an explicitly-provided id is
// still accepted.
describe('identity-column primary keys', () => {
  context('a model with a bigint identity primary key', () => {
    it('auto-assigns the id when none is provided', async () => {
      const user = await User.create({ email: 'fred@frewd', password: 'howyadoin' })
      expect(user.id).not.toBeNull()
      expect(typeof user.id).toBe('string')

      const reloaded = await User.find(user.id)
      expect(reloaded!.email).toEqual('fred@frewd')
    })

    it('accepts an explicitly-provided id', async () => {
      const user = await User.create({ id: '8675309', email: 'jenny@frewd', password: 'howyadoin' })
      expect(user.id).toEqual('8675309')

      const reloaded = await User.find('8675309')
      expect(reloaded!.email).toEqual('jenny@frewd')
    })
  })

  context('a model with an integer identity primary key', () => {
    it('auto-assigns the id when none is provided', async () => {
      const model = await ModelWithSerialPrimaryKey.create()
      expect(model.id).not.toBeNull()

      const reloaded = await ModelWithSerialPrimaryKey.find(model.id)
      expect(reloaded).not.toBeNull()
    })

    it('accepts an explicitly-provided id', async () => {
      const model = await ModelWithSerialPrimaryKey.create({ id: 8675309 })
      expect(model.id).toEqual(8675309)

      const reloaded = await ModelWithSerialPrimaryKey.find(8675309)
      expect(reloaded!.id).toEqual(8675309)
    })
  })
})
