import { DateTime } from 'luxon'
import {
  BalloonColorsEnumValues,
  BalloonLineMaterialsEnumValues,
  BalloonTypesEnumValues,
  CatTreatsValues,
  ExtraRateableTypesEnumValues,
  ExtraRatingTypesEnumValues,
  LocalesEnumValues,
  LocalizableTypesEnumValues,
  SpeciesValues,
  BalloonColorsEnum,
  BalloonLineMaterialsEnum,
  BalloonTypesEnum,
  CatTreats,
  ExtraRateableTypesEnum,
  ExtraRatingTypesEnum,
  Json,
  LocalesEnum,
  LocalizableTypesEnum,
  Species,
  IdType,
  Timestamp
} from './sync'

export const schema = {
  balloon_lines: {
    columns: {
      balloonId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      material: {
        coercedType: {} as BalloonLineMaterialsEnum | null,
        enumType: {} as BalloonLineMaterialsEnum,
        enumValues: BalloonLineMaterialsEnumValues,
        dbType: 'balloon_line_materials_enum',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      balloon: {
        type: 'BelongsTo',
        foreignKey: 'balloonId',
        tables: ['beautiful_balloons'],
        optional: false,
      },
    },
  },
  balloon_spotter_balloons: {
    columns: {
      balloonId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      balloonSpotterId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      userId: {
        coercedType: {} as IdType | null,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: true,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      balloon: {
        type: 'BelongsTo',
        foreignKey: 'balloonId',
        tables: ['beautiful_balloons'],
        optional: false,
      },
      balloonSpotter: {
        type: 'BelongsTo',
        foreignKey: 'balloonSpotterId',
        tables: ['balloon_spotters'],
        optional: false,
      },
      user: {
        type: 'BelongsTo',
        foreignKey: 'userId',
        tables: ['users'],
        optional: true,
      },
    },
  },
  balloon_spotters: {
    columns: {
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      name: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      balloonSpotterBalloons: {
        type: 'HasMany',
        foreignKey: 'balloonSpotterId',
        tables: ['balloon_spotter_balloons'],
        optional: null,
      },
      balloons: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['beautiful_balloons'],
        optional: null,
      },
      users: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['users'],
        optional: null,
      },
    },
  },
  beautiful_balloons: {
    columns: {
      color: {
        coercedType: {} as BalloonColorsEnum | null,
        enumType: {} as BalloonColorsEnum,
        enumValues: BalloonColorsEnumValues,
        dbType: 'balloon_colors_enum',
        allowNull: true,
        isArray: false,
      },
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      deletedAt: {
        coercedType: {} as DateTime | null,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: true,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      multicolor: {
        coercedType: {} as BalloonColorsEnum[] | null,
        enumType: {} as BalloonColorsEnum,
        enumValues: BalloonColorsEnumValues,
        dbType: 'balloon_colors_enum[]',
        allowNull: true,
        isArray: true,
      },
      positionAlpha: {
        coercedType: {} as number | null,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: true,
        isArray: false,
      },
      positionBeta: {
        coercedType: {} as number | null,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: true,
        isArray: false,
      },
      type: {
        coercedType: {} as BalloonTypesEnum,
        enumType: {} as BalloonTypesEnum,
        enumValues: BalloonTypesEnumValues,
        dbType: 'balloon_types_enum',
        allowNull: false,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      userId: {
        coercedType: {} as IdType | null,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: true,
        isArray: false,
      },
      volume: {
        coercedType: {} as number | null,
        enumType: null,
        enumValues: null,
        dbType: 'numeric',
        allowNull: true,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      balloonLine: {
        type: 'HasOne',
        foreignKey: 'balloonId',
        tables: ['balloon_lines'],
        optional: null,
      },
      heartRatings: {
        type: 'HasMany',
        foreignKey: 'extraRateableId',
        tables: ['extra_ratings'],
        optional: null,
      },
      sandbags: {
        type: 'HasMany',
        foreignKey: 'balloonId',
        tables: ['sandbags'],
        optional: null,
      },
      user: {
        type: 'BelongsTo',
        foreignKey: 'userId',
        tables: ['users'],
        optional: true,
      },
    },
  },
  collars: {
    columns: {
      balloonId: {
        coercedType: {} as IdType | null,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: true,
        isArray: false,
      },
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      hidden: {
        coercedType: {} as boolean | null,
        enumType: null,
        enumValues: null,
        dbType: 'boolean',
        allowNull: true,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      lost: {
        coercedType: {} as boolean | null,
        enumType: null,
        enumValues: null,
        dbType: 'boolean',
        allowNull: true,
        isArray: false,
      },
      petId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      position: {
        coercedType: {} as number,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: false,
        isArray: false,
      },
      tagName: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      balloon: {
        type: 'BelongsTo',
        foreignKey: 'balloonId',
        tables: ['beautiful_balloons'],
        optional: true,
      },
      pet: {
        type: 'BelongsTo',
        foreignKey: 'petId',
        tables: ['pets'],
        optional: false,
      },
    },
  },
  composition_asset_audits: {
    columns: {
      approval: {
        coercedType: {} as boolean | null,
        enumType: null,
        enumValues: null,
        dbType: 'boolean',
        allowNull: true,
        isArray: false,
      },
      compositionAssetId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      notes: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'text',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      composition: {
        type: 'HasOne',
        foreignKey: 'compositionAssetAuditId',
        tables: ['compositions'],
        optional: null,
      },
      compositionAsset: {
        type: 'BelongsTo',
        foreignKey: 'compositionAssetId',
        tables: ['composition_assets'],
        optional: false,
      },
      user: {
        type: 'HasOne',
        foreignKey: 'compositionAssetAuditId',
        tables: ['users'],
        optional: null,
      },
    },
  },
  composition_assets: {
    columns: {
      compositionId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      name: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      primary: {
        coercedType: {} as boolean | null,
        enumType: null,
        enumValues: null,
        dbType: 'boolean',
        allowNull: true,
        isArray: false,
      },
      score: {
        coercedType: {} as number | null,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: true,
        isArray: false,
      },
      src: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'text',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      composition: {
        type: 'BelongsTo',
        foreignKey: 'compositionId',
        tables: ['compositions'],
        optional: false,
      },
      compositionAssetAudits: {
        type: 'HasMany',
        foreignKey: 'compositionAssetId',
        tables: ['composition_asset_audits'],
        optional: null,
      },
      currentLocalizedText: {
        type: 'HasOne',
        foreignKey: 'localizableId',
        tables: ['localized_texts'],
        optional: null,
      },
      localizedTexts: {
        type: 'HasMany',
        foreignKey: 'localizableId',
        tables: ['localized_texts'],
        optional: null,
      },
      user: {
        type: 'HasOne',
        foreignKey: 'compositionAssetId',
        tables: ['users'],
        optional: null,
      },
    },
  },
  compositions: {
    columns: {
      content: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'text',
        allowNull: true,
        isArray: false,
      },
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      metadata: {
        coercedType: {} as Json,
        enumType: null,
        enumValues: null,
        dbType: 'jsonb',
        allowNull: false,
        isArray: false,
      },
      metadata2: {
        coercedType: {} as Json | null,
        enumType: null,
        enumValues: null,
        dbType: 'jsonb',
        allowNull: true,
        isArray: false,
      },
      metadata3: {
        coercedType: {} as Json | null,
        enumType: null,
        enumValues: null,
        dbType: 'json',
        allowNull: true,
        isArray: false,
      },
      primary: {
        coercedType: {} as boolean | null,
        enumType: null,
        enumValues: null,
        dbType: 'boolean',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      userId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      compositionAssetAudits: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['composition_asset_audits'],
        optional: null,
      },
      compositionAssets: {
        type: 'HasMany',
        foreignKey: 'compositionId',
        tables: ['composition_assets'],
        optional: null,
      },
      currentLocalizedText: {
        type: 'HasOne',
        foreignKey: 'localizableId',
        tables: ['localized_texts'],
        optional: null,
      },
      heartRatings: {
        type: 'HasMany',
        foreignKey: 'extraRateableId',
        tables: ['extra_ratings'],
        optional: null,
      },
      localizedTexts: {
        type: 'HasMany',
        foreignKey: 'localizableId',
        tables: ['localized_texts'],
        optional: null,
      },
      mainCompositionAsset: {
        type: 'HasOne',
        foreignKey: 'compositionId',
        tables: ['composition_assets'],
        optional: null,
      },
      mainCompositionAssetAudits: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['composition_asset_audits'],
        optional: null,
      },
      user: {
        type: 'BelongsTo',
        foreignKey: 'userId',
        tables: ['users'],
        optional: false,
      },
    },
  },
  edge_case_attributes: {
    columns: {
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      kPop: {
        coercedType: {} as boolean | null,
        enumType: null,
        enumValues: null,
        dbType: 'boolean',
        allowNull: true,
        isArray: false,
      },
      popK: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      popKPop: {
        coercedType: {} as number | null,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      
    },
  },
  extra_ratings: {
    columns: {
      body: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'text',
        allowNull: true,
        isArray: false,
      },
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      extraRateableId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      extraRateableType: {
        coercedType: {} as ExtraRateableTypesEnum,
        enumType: {} as ExtraRateableTypesEnum,
        enumValues: ExtraRateableTypesEnumValues,
        dbType: 'extra_rateable_types_enum',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      rating: {
        coercedType: {} as number | null,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: true,
        isArray: false,
      },
      type: {
        coercedType: {} as ExtraRatingTypesEnum,
        enumType: {} as ExtraRatingTypesEnum,
        enumValues: ExtraRatingTypesEnumValues,
        dbType: 'extra_rating_types_enum',
        allowNull: false,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      userId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      extraRateable: {
        type: 'BelongsTo',
        foreignKey: 'extraRateableId',
        tables: ['compositions', 'posts', 'beautiful_balloons'],
        optional: false,
      },
      user: {
        type: 'BelongsTo',
        foreignKey: 'userId',
        tables: ['users'],
        optional: false,
      },
    },
  },
  graph_edge_nodes: {
    columns: {
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      edgeId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      multiScopedPosition: {
        coercedType: {} as number,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: false,
        isArray: false,
      },
      nodeId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      position: {
        coercedType: {} as number,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: false,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      edge: {
        type: 'BelongsTo',
        foreignKey: 'edgeId',
        tables: ['graph_edges'],
        optional: false,
      },
      headSibling: {
        type: 'HasOne',
        foreignKey: 'graphEdgeNodeId',
        tables: ['graph_edge_nodes'],
        optional: null,
      },
      justThisSibling: {
        type: 'HasOne',
        foreignKey: 'graphEdgeNodeId',
        tables: ['graph_edge_nodes'],
        optional: null,
      },
      node: {
        type: 'BelongsTo',
        foreignKey: 'nodeId',
        tables: ['graph_nodes'],
        optional: false,
      },
      orderedSiblings: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['graph_edge_nodes'],
        optional: null,
      },
      orderedSiblingsWithOrderOnSource: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['graph_edge_nodes'],
        optional: null,
      },
      siblings: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['graph_edge_nodes'],
        optional: null,
      },
      siblingsIncludingMe: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['graph_edge_nodes'],
        optional: null,
      },
      tailSiblings: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['graph_edge_nodes'],
        optional: null,
      },
    },
  },
  graph_edges: {
    columns: {
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      name: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      weight: {
        coercedType: {} as number | null,
        enumType: null,
        enumValues: null,
        dbType: 'numeric',
        allowNull: true,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      edgeNodes: {
        type: 'HasMany',
        foreignKey: 'edgeId',
        tables: ['graph_edge_nodes'],
        optional: null,
      },
      nodes: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['graph_nodes'],
        optional: null,
      },
    },
  },
  graph_nodes: {
    columns: {
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      name: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      omittedEdgePosition: {
        coercedType: {} as number | null,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      edgeNodes: {
        type: 'HasMany',
        foreignKey: 'nodeId',
        tables: ['graph_edge_nodes'],
        optional: null,
      },
      edges: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['graph_edges'],
        optional: null,
      },
      edgesOrderedByName: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['graph_edges'],
        optional: null,
      },
      edgesOrderedByPosition: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['graph_edges'],
        optional: null,
      },
      nonNodeNameEdgesOnThroughAssociation: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['graph_edges'],
        optional: null,
      },
      nonOmittedPositionEdgeNodes: {
        type: 'HasMany',
        foreignKey: 'nodeId',
        tables: ['graph_edge_nodes'],
        optional: null,
      },
      nonOmittedPositionEdges: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['graph_edges'],
        optional: null,
      },
      orderedEdgeNodes: {
        type: 'HasMany',
        foreignKey: 'nodeId',
        tables: ['graph_edge_nodes'],
        optional: null,
      },
    },
  },
  incompatible_foreign_key_type_examples: {
    columns: {
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      userId: {
        coercedType: {} as number,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      user: {
        type: 'BelongsTo',
        foreignKey: 'userId',
        tables: ['users'],
        optional: false,
      },
    },
  },
  localized_texts: {
    columns: {
      body: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'text',
        allowNull: true,
        isArray: false,
      },
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      locale: {
        coercedType: {} as LocalesEnum,
        enumType: {} as LocalesEnum,
        enumValues: LocalesEnumValues,
        dbType: 'locales_enum',
        allowNull: false,
        isArray: false,
      },
      localizableId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      localizableType: {
        coercedType: {} as LocalizableTypesEnum,
        enumType: {} as LocalizableTypesEnum,
        enumValues: LocalizableTypesEnumValues,
        dbType: 'localizable_types_enum',
        allowNull: false,
        isArray: false,
      },
      name: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      title: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      localizable: {
        type: 'BelongsTo',
        foreignKey: 'localizableId',
        tables: ['compositions', 'composition_assets'],
        optional: false,
      },
    },
  },
  model_without_updated_at: {
    columns: {
      cantUpdateThis: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      name: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      
    },
  },
  pet_understudy_join_models: {
    columns: {
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      petId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      understudyId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      pet: {
        type: 'BelongsTo',
        foreignKey: 'petId',
        tables: ['pets'],
        optional: false,
      },
      understudy: {
        type: 'BelongsTo',
        foreignKey: 'understudyId',
        tables: ['pets'],
        optional: false,
      },
    },
  },
  pets: {
    columns: {
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      deletedAt: {
        coercedType: {} as DateTime | null,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: true,
        isArray: false,
      },
      favoriteDaysOfWeek: {
        coercedType: {} as number[] | null,
        enumType: null,
        enumValues: null,
        dbType: 'integer[]',
        allowNull: true,
        isArray: true,
      },
      favoriteTreats: {
        coercedType: {} as CatTreats[] | null,
        enumType: {} as CatTreats,
        enumValues: CatTreatsValues,
        dbType: 'cat_treats[]',
        allowNull: true,
        isArray: true,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      name: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'text',
        allowNull: true,
        isArray: false,
      },
      nickname: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'text',
        allowNull: true,
        isArray: false,
      },
      positionWithinSpecies: {
        coercedType: {} as number,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: false,
        isArray: false,
      },
      species: {
        coercedType: {} as Species | null,
        enumType: {} as Species,
        enumValues: SpeciesValues,
        dbType: 'species',
        allowNull: true,
        isArray: false,
      },
      userId: {
        coercedType: {} as IdType | null,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: true,
        isArray: false,
      },
      userUuid: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'uuid',
        allowNull: true,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      collars: {
        type: 'HasMany',
        foreignKey: 'petId',
        tables: ['collars'],
        optional: null,
      },
      currentCollar: {
        type: 'HasOne',
        foreignKey: 'petId',
        tables: ['collars'],
        optional: null,
      },
      distinctBalloons: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['beautiful_balloons'],
        optional: null,
      },
      featuredPost: {
        type: 'HasOne',
        foreignKey: 'petId',
        tables: ['posts'],
        optional: null,
      },
      featuredRatings: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['ratings'],
        optional: null,
      },
      notLostCollar: {
        type: 'HasOne',
        foreignKey: 'petId',
        tables: ['collars'],
        optional: null,
      },
      notRedBalloons: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['beautiful_balloons'],
        optional: null,
      },
      petUnderstudies: {
        type: 'HasMany',
        foreignKey: 'petId',
        tables: ['pet_understudy_join_models'],
        optional: null,
      },
      ratings: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['ratings'],
        optional: null,
      },
      redBalloons: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['beautiful_balloons'],
        optional: null,
      },
      understudies: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['pets'],
        optional: null,
      },
      uniqueBalloons: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['beautiful_balloons'],
        optional: null,
      },
      uniqueCollars: {
        type: 'HasMany',
        foreignKey: 'petId',
        tables: ['collars'],
        optional: null,
      },
      user: {
        type: 'BelongsTo',
        foreignKey: 'userId',
        tables: ['users'],
        optional: true,
      },
      userThroughUuid: {
        type: 'BelongsTo',
        foreignKey: 'userUuid',
        tables: ['users'],
        optional: true,
      },
    },
  },
  post_visibilities: {
    columns: {
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      notes: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'text',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      visibility: {
        coercedType: {} as boolean | null,
        enumType: null,
        enumValues: null,
        dbType: 'boolean',
        allowNull: true,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      post: {
        type: 'HasOne',
        foreignKey: 'postVisibilityId',
        tables: ['posts'],
        optional: null,
      },
    },
  },
  posts: {
    columns: {
      body: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'text',
        allowNull: true,
        isArray: false,
      },
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      deletedAt: {
        coercedType: {} as DateTime | null,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: true,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      position: {
        coercedType: {} as number,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: false,
        isArray: false,
      },
      postVisibilityId: {
        coercedType: {} as IdType | null,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      userId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      heartRatings: {
        type: 'HasMany',
        foreignKey: 'extraRateableId',
        tables: ['extra_ratings'],
        optional: null,
      },
      postVisibility: {
        type: 'BelongsTo',
        foreignKey: 'postVisibilityId',
        tables: ['post_visibilities'],
        optional: true,
      },
      ratings: {
        type: 'HasMany',
        foreignKey: 'rateableId',
        tables: ['ratings'],
        optional: null,
      },
      user: {
        type: 'BelongsTo',
        foreignKey: 'userId',
        tables: ['users'],
        optional: false,
      },
    },
  },
  ratings: {
    columns: {
      body: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'text',
        allowNull: true,
        isArray: false,
      },
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      rateableId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      rateableType: {
        coercedType: {} as string,
        enumType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: false,
        isArray: false,
      },
      rating: {
        coercedType: {} as number | null,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      userId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      rateable: {
        type: 'BelongsTo',
        foreignKey: 'rateableId',
        tables: ['compositions', 'posts'],
        optional: false,
      },
      user: {
        type: 'BelongsTo',
        foreignKey: 'userId',
        tables: ['users'],
        optional: false,
      },
    },
  },
  sandbags: {
    columns: {
      balloonId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      weight: {
        coercedType: {} as number | null,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: true,
        isArray: false,
      },
      weightKgs: {
        coercedType: {} as number | null,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: true,
        isArray: false,
      },
      weightTons: {
        coercedType: {} as number | null,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: true,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      mylar: {
        type: 'BelongsTo',
        foreignKey: 'balloonId',
        tables: ['beautiful_balloons'],
        optional: false,
      },
    },
  },
  user_settings: {
    columns: {
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      likesChalupas: {
        coercedType: {} as boolean,
        enumType: null,
        enumValues: null,
        dbType: 'boolean',
        allowNull: false,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      userId: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      user: {
        type: 'BelongsTo',
        foreignKey: 'userId',
        tables: ['users'],
        optional: false,
      },
    },
  },
  users: {
    columns: {
      birthdate: {
        coercedType: {} as DateTime | null,
        enumType: null,
        enumValues: null,
        dbType: 'date',
        allowNull: true,
        isArray: false,
      },
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      deletedAt: {
        coercedType: {} as DateTime | null,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: true,
        isArray: false,
      },
      email: {
        coercedType: {} as string,
        enumType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: false,
        isArray: false,
      },
      favoriteDates: {
        coercedType: {} as Timestamp[] | null,
        enumType: null,
        enumValues: null,
        dbType: 'date[]',
        allowNull: true,
        isArray: true,
      },
      favoriteDatetimes: {
        coercedType: {} as Timestamp[] | null,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone[]',
        allowNull: true,
        isArray: true,
      },
      favoriteNumbers: {
        coercedType: {} as number[] | null,
        enumType: null,
        enumValues: null,
        dbType: 'integer[]',
        allowNull: true,
        isArray: true,
      },
      favoriteWord: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'citext',
        allowNull: true,
        isArray: false,
      },
      featuredPostPosition: {
        coercedType: {} as number | null,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: true,
        isArray: false,
      },
      id: {
        coercedType: {} as IdType,
        enumType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      name: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      passwordDigest: {
        coercedType: {} as string,
        enumType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: false,
        isArray: false,
      },
      socialSecurityNumber: {
        coercedType: {} as string | null,
        enumType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      targetRating: {
        coercedType: {} as number | null,
        enumType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      uuid: {
        coercedType: {} as string,
        enumType: null,
        enumValues: null,
        dbType: 'uuid',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: ['password'],
    associations: {
      balloonLines: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['balloon_lines'],
        optional: null,
      },
      balloons: {
        type: 'HasMany',
        foreignKey: 'userId',
        tables: ['beautiful_balloons'],
        optional: null,
      },
      balloonsFromUuid: {
        type: 'HasMany',
        foreignKey: 'userId',
        tables: ['beautiful_balloons'],
        optional: null,
      },
      collarsFromUuid: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['collars'],
        optional: null,
      },
      compositionAssetAudits: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['composition_asset_audits'],
        optional: null,
      },
      compositionAssets: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['composition_assets'],
        optional: null,
      },
      compositions: {
        type: 'HasMany',
        foreignKey: 'userId',
        tables: ['compositions'],
        optional: null,
      },
      featuredPost: {
        type: 'HasOne',
        foreignKey: 'userId',
        tables: ['posts'],
        optional: null,
      },
      featuredRatings: {
        type: 'HasMany',
        foreignKey: 'userId',
        tables: ['ratings'],
        optional: null,
      },
      firstCollarFromUuid: {
        type: 'HasOne',
        foreignKey: 'userId',
        tables: ['collars'],
        optional: null,
      },
      firstComposition: {
        type: 'HasOne',
        foreignKey: 'userId',
        tables: ['compositions'],
        optional: null,
      },
      firstComposition2: {
        type: 'HasOne',
        foreignKey: 'userId',
        tables: ['compositions'],
        optional: null,
      },
      firstPet: {
        type: 'HasOne',
        foreignKey: 'userId',
        tables: ['pets'],
        optional: null,
      },
      firstPetFromUuid: {
        type: 'HasOne',
        foreignKey: 'userUuid',
        tables: ['pets'],
        optional: null,
      },
      incompatibleForeignKeyTypeExamples: {
        type: 'HasMany',
        foreignKey: 'userId',
        tables: ['incompatible_foreign_key_type_examples'],
        optional: null,
      },
      lastComposition: {
        type: 'HasOne',
        foreignKey: 'userId',
        tables: ['compositions'],
        optional: null,
      },
      mainComposition: {
        type: 'HasOne',
        foreignKey: 'userId',
        tables: ['compositions'],
        optional: null,
      },
      mainCompositionAsset: {
        type: 'HasOne',
        foreignKey: 'userId',
        tables: ['composition_assets'],
        optional: null,
      },
      nonExtantCompositionAssets1: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['composition_assets'],
        optional: null,
      },
      nonExtantCompositionAssets2: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['composition_assets'],
        optional: null,
      },
      notRecentCompositions: {
        type: 'HasMany',
        foreignKey: 'userId',
        tables: ['compositions'],
        optional: null,
      },
      pets: {
        type: 'HasMany',
        foreignKey: 'userId',
        tables: ['pets'],
        optional: null,
      },
      petsFromUuid: {
        type: 'HasMany',
        foreignKey: 'userUuid',
        tables: ['pets'],
        optional: null,
      },
      postRatings: {
        type: 'HasMany',
        foreignKey: 'userId',
        tables: ['ratings'],
        optional: null,
      },
      posts: {
        type: 'HasMany',
        foreignKey: 'userId',
        tables: ['posts'],
        optional: null,
      },
      ratings: {
        type: 'HasMany',
        foreignKey: 'userId',
        tables: ['ratings'],
        optional: null,
      },
      ratingsThroughPostsThatMatchUserTargetRating: {
        type: 'HasMany',
        foreignKey: 'userId',
        tables: ['ratings'],
        optional: null,
      },
      recentCompositionAssets: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['composition_assets'],
        optional: null,
      },
      recentCompositions: {
        type: 'HasMany',
        foreignKey: 'userId',
        tables: ['compositions'],
        optional: null,
      },
      recentMainCompositionAssets: {
        type: 'HasMany',
        foreignKey: null,
        tables: ['composition_assets'],
        optional: null,
      },
      sortedCompositions: {
        type: 'HasMany',
        foreignKey: 'userId',
        tables: ['compositions'],
        optional: null,
      },
      sortedCompositions2: {
        type: 'HasMany',
        foreignKey: 'userId',
        tables: ['compositions'],
        optional: null,
      },
      userSettings: {
        type: 'HasOne',
        foreignKey: 'userId',
        tables: ['user_settings'],
        optional: null,
      },
    },
  },
} as const
